// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/pogr_api_golang_aneesh_jose/profile_achievements/src/models"
	mock "github.com/stretchr/testify/mock"
)

// AchievementsService is an autogenerated mock type for the AchievementsService type
type AchievementsService struct {
	mock.Mock
}

// GetUserAchievements provides a mock function with given fields: ctx, userID
func (_m *AchievementsService) GetUserAchievements(ctx context.Context, userID string) ([]models.Achievement, error) {
	ret := _m.Called(ctx, userID)

	var r0 []models.Achievement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.Achievement, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Achievement); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Achievement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAchievementsService interface {
	mock.TestingT
	Cleanup(func())
}

// NewAchievementsService creates a new instance of AchievementsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAchievementsService(t mockConstructorTestingTNewAchievementsService) *AchievementsService {
	mock := &AchievementsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
